warehouse:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: First2000
      dbname: dvdrental
      schema: public

    prod:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: "{{ env_var('PGUID') }}"
      pass: "{{ env_var('PGPASS') }}"
      dbname: adventureworks
      schema: public

  target: dev

